### ISSUE TITLE
Envio de e-mails de confirmação com QRCode

### ISSUE THREAD

**Issue by wgbn** [lfdev-gdg/landingpage-evento#1]
Criar um mecanismo para envio de e-mail de confirmação para cada inscrição realizada.
O e-mail deve conter um QRCode com o código do usuário.

Este QRCode será usado no dia do evento para fazer o checkin do participante, sorteios, etc.

**Comment by dannyserena** [comment]
QrCode já está sendo impresso, podemos fechar essa issue?

**Comment by wgbn** [comment]
Tinha esqueciso. Sim, estamos usando a api http://goqr.me/api/ para gerar os qrcodes e enviando por emauil de confirmação
