### ISSUE TITLE
Convite - Primeiro Meetup GDG Lauro de Freitas

### ISSUE THREAD

**Issue by dannyserena** [lfdev-gdg/landingpage-evento#3]
Você é apaixonado por tecnologias? Então vem com a gente para o primeiro encontro do **GDG de Lauro de Freitas!** 

O Google Developer Group  é uma comunidade que reúne desenvolvedores independentes, apaixonados por tecnologia e formada por voluntários.
 
Nosso encontro será na faculdade Maurício de Nassau no dia 01/04. Confira a grade de palestras e garanta logo a sua entrada, pois as vagas são limitadas. Nos vemos lá!

#gdglaurodefreitas #talks #lfdev
Inscrição: http://evento.lfdev.tk/
Blog: https://blog.lfdev.tk

**Comment by fxcosta** [comment]
@dannyserena já mandou com esse texto, né? então já foi, nem precisa de votação mais, hehe, pode fechar a issue se estiver pronto.

**Comment by wgbn** [comment]
verdade, mais uma resolvida. hahahahha
