### ISSUE TITLE
Página confirmação de inscrição faltando botão

### ISSUE THREAD

**Issue by dannyserena** [lfdev-gdg/landingpage-evento#6]
Editar a page de confirmação de inscrição pois não se cadastrar, além dá mensagem de cadastro só há botão de "cancelar", deixando o usuário preso na tela.

**Comment by wgbn** [comment]
Sinceramente não entendi  a dúvida, há uma mensagem dizendo que a inscrição foi concluída e que um email foi enviado

**Comment by wgbn** [comment]
resolvido com o ultimo commit
